### ISSUE TITLE
how to convert json file from Supervisely to KITTI label format  

### ISSUE THREAD

**Issue by zjx99** [Gltina/ACP-3Detection#1]
Hi, Gltina, 
Thank you for proving this wonderful repository.
I tried to use Supervisely to annotate my lidar data and I got a simple json file. The labels in json are quite different from those in KITTI label.  You provided  a tool to convert json to KITTI label , however, I am wondering if you have done any other conversion before feeding json( as below) to  converter_mylabel2KITTIlabel.py since there were errors putting json directly into this function.  If so, how did you do that?  Thanks. 
![image](https://user-images.githubusercontent.com/35533389/98798608-f8a60b80-2405-11eb-9a09-d2a68ab9c170.png)
![image](https://user-images.githubusercontent.com/35533389/98798354-b4b30680-2405-11eb-834d-bcf7283390c6.png)

**Comment by leihui6** [comment]
Hi @zjx99 ,

Thanks for your attention. I notice that the JSON file in your example is different from ours, generated from the **download** button on "https://3d.supervise.ly/projects/". We guarantee the JSON having a special format(**_3d.supervise.ly_** style) could be converted correctly.

For your problem, could you please tell me how do you obtain your JSON file?

**Comment by zjx99** [comment]
Hi, Gltina,
Thank you. I was recommended by the customer service to use a new version of Supervisely: https://app.supervise.ly/. What I did to obtain the JSON file is as follows: 
![image](https://user-images.githubusercontent.com/35533389/98966443-32107100-2503-11eb-96f4-e168d0582c78.png)

**Comment by zjx99** [comment]
Hi, Gltina, 
Sorry, but I  still don't quite understand how to do the conversion.  Can you be a little more specific?   Thank you so much!

**Comment by leihui6** [comment]
Hi @zjx99 ,

For a good understanding, I added JSON files in [here](https://github.com/Gltina/ACP-3Detection/tree/master/tools/converter_label/rough_detection) ([README](https://github.com/Gltina/ACP-3Detection/tree/master/tools)), hope it could be helpful to you.

By the way, I think you should use `https://3d.supervise.ly/projects/` or _**Download as .json (without point clouds)**_.

**Comment by leihui6** [comment]
Hi @zjx99,

Thanks for your reminder. 

Due to the upgrade of [supervise.ly](https://app.supervise.ly/projects/), the **older label file (*.json)** can not be used after _**30 Nov 2020**_. 

To make converter tools in this repository still be OK, we updated our tools recently. However, this website doesn't allow us to transfer point cloud data and the labeled files we've done before. So from now, we don't have enough data to do testing about converting its file to the KITTI label.

We are so happy to hear that you are ganna use these tools and issue us.

**Comment by zjx99** [comment]
Hi, Lei Hui,

Thank you for the reply.

I have used the provided tools to convert json to kitti label. Now I still have two questions:

1.  What is the original format of your lidar data?  Is it originally in bin file ?  If not, how did you convert them to bin before transforming to    KITTI format? My data is in csv file, so I tried to convert them to bin and replace those KITTI bins in the kitti data folder in training.        However, I couldn't make it go through.  When I tried to convert the bin back to csv, I got strange values, so I assume that the conversion from csv to bin is not right.

2. How did you do the visualization?  I couldn't manage to do it on a remote server using the provided module.  I am trying to save the
detection results which are in pkl files and visualize them through another repository (https://github.com/kuixu/kitti_object_vis). However, it seems that the input label file should be in the same format as KITTI training label.  I have no idea how to transform the pkl file to kitti label file.

Could you please give me some advice on the above questions?  Thanks a lot.

Best,
Jiaxing


________________________________

**Comment by AsiDiaz** [comment]
Hi @Gltina,

I am triying to convert json file generated from supervise into label files with your script but I am not succeeding. I obtained the JSON file  with out point clouds downloading it from supervise. When I use the script with the next command, it generates a file to store labels but it is empty. 
`python3 converter_mylabel2KITTIlabel.py -i /home/asier/KITTI_labels/labels/Prueba_labels/pcd_pertsona1Hz/ann -o KITTI_label_rough` 

I don't know the reason so I would like to ask for your help. I also attach an example of my JSON files [labels.zip](https://github.com/Gltina/ACP-3Detection/files/8325331/labels.zip).

**Comment by russellyq** [comment]
Hi @gltina ,

Thanks for your work.

I am confused about this line: https://github.com/gltina/ACP-3Detection/blob/dc5623686c86e048dffa95fc86ebf4452e36e548/tools/converter_label/rough_detection/current_version/converter_mylabel2KITTIlabel.py#L92

**Comment by eldos87** [comment]
Hi there,

In the provided code for conversion, I didn't understand 2 lines as below:

### the height of velodyne camera 
camera_height = -1.73                              -> How do we get this information??

position[0] = position[0] - 0.27                -> Why minus off 0.27??

Could you please explain?
