### ISSUE TITLE
How to get evaluation result on own dataset

### ISSUE THREAD

**Issue by Jane-QinJ** [Gltina/ACP-3Detection#10]
Hi Gltina, thanks for your amazing work.

I used the custom dataset method that u mentioned in [here](https://github.com/Gltina/ACP-3Detection/issues/2). And I've get some not bad result which is in KITTI format. So I want to evaluate the result, but the kitti evaluation is not support for my custom result, so I read your paper, and want to use your method to get overlap volumes between ground truth and final_result.

I tried to use the [evaluation.py](https://github.com/Gltina/ACP-3Detection/blob/master/tools/evaluation/evaluation.py) code that u have made, but I can't get the right result, which I think should output the overlap volumes. 
I put the trained and standard label fold as u mentioned: 
![image](https://user-images.githubusercontent.com/42195412/163577022-e6b03c6b-f49f-4dfb-aac7-35a86120285c.png)

and I get the result :
![image](https://user-images.githubusercontent.com/42195412/163577460-ff92dac6-115d-4599-a2b2-24626dab2bc3.png)

This is the command that I input:
`evaluation.py trained_label`

and the standard label example:
`tractor 0.00 0 0.00 0 0 50 50 2.74 2.12 4.33 4.28 1.28 5.2 0.0`

the trained label example:
`tractor -1 -1 -3.8309 0.0000 0.0000 0.0000 0.0000 2.5715 2.2279 4.3080 4.1810 1.2036 5.1874 -3.1535 0.9790`

I would appreciate it if you can help me figure out where is my problem,  many thanks to u in advance.

**Comment by leihui6** [comment]
Could I ask that what is the trained label? is it the result provided by 3D detection framework? btw, the evaluation tools are new released by OpenPCDet officially. 

The evaluation we used will be released soon later this year!
