### ISSUE TITLE
Question about the 7m in the pointcould converter

### ISSUE THREAD

**Issue by udacityyy** [Gltina/ACP-3Detection#12]
Hello, first of all thank you for you work,
I wanted to ask why did you chose to move the scene of 7m exactly ( it worked better for me as well but I'm wondering why)
I was in a comment that, for kitti, the scene is a bit far from the center (velodyne), but i wanted to know the exact reason why 7m or was it just a choice ?

Thanks in advance

**Comment by leihui6** [comment]
It depends on your practical application, for me, the 7m is used for moving the point cloud of object along with the x-axis, and to be the center of focal point of 3D camera.
