### ISSUE TITLE
Doubts in X-Y-Z (Supervisley cordinate system) to Kitty Camera(X-Y-Z)

### ISSUE THREAD

**Issue by Manueljohnson063** [Gltina/ACP-3Detection#4]

**Comment by Manueljohnson063** [comment]
Hai Madam could you please give me an insight :(

**Comment by Manueljohnson063** [comment]
> @Gltina Hai Madam could you please give me an insight :(

**Comment by leihui6** [comment]
@Manueljohnson063 we recommend you use the CloudCompare or MeshLab to check the coordinate of them.
