### ISSUE TITLE
Regarding the output given dataset(Fine)

### ISSUE THREAD

**Issue by Manueljohnson063** [Gltina/ACP-3Detection#6]
Hai,
I had used your pretrained model given **checkpoint_epoch_250.pth**  and your data(Fine) to check the output but when I use the **demo.py** I got the output as [below. I didn't get the output as yours given in the .gif file
![GLITINA](https://user-images.githubusercontent.com/44712542/129029387-3108e27d-9b5b-4f13-862f-c43fe742a681.PNG)
**ie No 3d Box**

**Comment by leihui6** [comment]
I found that you are using the models for Socket/Plug, which is a type of small object. The pre-processing of the point cloud from 3D devices is required. According to your questions, there are two points to be aware of. 

1) We amplified our data as [here](https://github.com/Gltina/ACP-3Detection/blob/master/tools/converter_data/fine_detection/converter_pc2KITTIpc.py#L43)
2) The target object we labeled may be different from yours, but even small diff I believe you still can get a detection result, so I hope the first could be helpful for you.
