### ISSUE TITLE
Train the model with custom dataset

### ISSUE THREAD

**Issue by devendraswamy** [Gltina/ACP-3Detection#9]
Please help me, is it possible to train the model with custom dataset , how can I train and inference the model with custom dataset , if possible please help me , Thank you so much in advance.

**Comment by leihui6** [comment]
Yes it is possible, now you can use the official tools provided from [OpenPCDet for training you own dataset](https://github.com/open-mmlab/OpenPCDet/blob/master/docs/CUSTOM_DATASET_TUTORIAL.md)

**Comment by devendraswamy** [comment]
Thank you so much for your valuable reply  , could you please tell me how to make 3d annotation from 2d Image , really is it possible ? Thank you.

**Comment by leihui6** [comment]
well, I don't think it is possible if you only have 2D image. there may be ways to do this but so far I have no ideas sorry
